# Generated by Django 5.0.6 on 2024-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing",
                    models.ManyToManyField(
                        related_name="bookmarkedListing", to="backend.listing"
                    ),
                ),
            ],
        ),
    ]
