# Generated by Django 5.0.6 on 2024-06-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0001_initial"),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="listing",
            field=models.ManyToManyField(to="listings.listing"),
        ),
    ]
