# Generated by Django 5.0.6 on 2024-06-25 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0003_alter_bookmark_listing_alter_bookmark_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bookmark",
            table="bookmarks",
        ),
    ]
