# Generated by Django 5.0.6 on 2024-06-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0004_alter_bookmark_table"),
        ("listings", "0012_alter_query_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="listing",
            field=models.ManyToManyField(to="listings.processedlistings"),
        ),
    ]
