# Generated by Django 5.0.6 on 2024-06-21 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processedlistings",
            old_name="unnamed_0",
            new_name="Unnamed",
        ),
    ]
