# Generated by Django 5.0.6 on 2024-06-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_alter_processedlistings_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="image",
        ),
        migrations.AlterField(
            model_name="processedlistings",
            name="image",
            field=models.URLField(),
        ),
    ]
