# Generated by Django 5.0.6 on 2024-06-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_alter_processedlistings_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedlistings",
            name="bathrooms",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="processedlistings",
            name="bedroom",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="processedlistings",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="processedlistings",
            name="pricepermonth",
            field=models.CharField(max_length=500),
        ),
    ]
