# Generated by Django 5.0.6 on 2024-06-25 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_remove_listing_image_alter_processedlistings_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="query",
            name="listing",
        ),
        migrations.AlterModelTable(
            name="image",
            table="listing_images",
        ),
    ]
