# Generated by Django 5.0.6 on 2024-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_processedlistings_bathrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bathrooms",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="bedroom",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="pricepermonth",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="listing",
            name="town",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="listing",
            name="views",
            field=models.IntegerField(),
        ),
    ]
