# Generated by Django 5.0.6 on 2024-06-25 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_remove_query_listing_alter_image_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_image",
                to="listings.listing",
            ),
        ),
    ]
