# Generated by Django 5.0.6 on 2024-06-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_alter_image_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedlistings",
            name="views",
            field=models.FloatField(),
        ),
    ]
