# Generated by Django 5.0.6 on 2024-06-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0006_alter_processedlistings_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="views",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="processedlistings",
            name="views",
            field=models.IntegerField(),
        ),
    ]
