# Generated by Django 5.0.6 on 2024-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_alter_listing_views_alter_processedlistings_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="views",
            field=models.IntegerField(),
        ),
    ]
