# Generated by Django 5.0.6 on 2024-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_alter_listing_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedlistings",
            name="listing",
            field=models.IntegerField(default=0),
        ),
    ]
