# Generated by Django 5.0.6 on 2024-06-25 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0010_alter_processedlistings_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processedlistings",
            name="Unnamed",
        ),
    ]
