# Generated by Django 5.0.6 on 2024-06-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0011_remove_processedlistings_unnamed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="query",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
