# Generated by Django 5.0.6 on 2024-06-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("image", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=200)),
                ("listing_type", models.CharField(max_length=50)),
                ("bedroom", models.CharField(max_length=200)),
                ("bathrooms", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=50)),
                ("town", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=200)),
                ("pricepermonth", models.CharField(max_length=50)),
                ("views", models.CharField(max_length=200)),
                ("reactions", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.client"
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InquiryMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sender", models.CharField(max_length=50)),
                ("message", models.TextField(max_length=1000)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.inquiry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookMark",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.client"
                    ),
                ),
                ("listing", models.ManyToManyField(to="backend.listing")),
            ],
        ),
        migrations.CreateModel(
            name="RealEstateAgent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                (
                    "inquirys",
                    models.ManyToManyField(
                        related_name="real_estate_agents", to="backend.inquiry"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inquiry",
            name="realestateagent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="backend.realestateagent",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.admin"
                    ),
                ),
                ("listings", models.ManyToManyField(to="backend.listing")),
            ],
        ),
    ]
